"""Adding image column

Revision ID: 721f8c35ff33
Revises: 8daeef7c4b24
Create Date: 2021-03-12 18:01:55.890495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721f8c35ff33'
down_revision = '8daeef7c4b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smash_characters', sa.Column('image', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smash_characters', 'image')
    # ### end Alembic commands ###
