"""Create Character table

Revision ID: 8daeef7c4b24
Revises: 
Create Date: 2021-03-12 17:22:40.002148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daeef7c4b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smash_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('dash_speed', sa.String(length=20), nullable=True),
    sa.Column('air_speed', sa.String(length=20), nullable=True),
    sa.Column('final_smash', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smash_characters')
    # ### end Alembic commands ###
